version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mangu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mangu_db
      POSTGRES_USER: mangu_user
      POSTGRES_PASSWORD: MxiXcjyvHot7BjuMuwUlmbYLqmv79jlH
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./server/src/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mangu_user -d mangu_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mangu-network

  redis:
    image: redis:7-alpine
    container_name: mangu-redis
    restart: unless-stopped
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass HtQory2wdk1X8M8YJuwjQ
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "HtQory2wdk1X8M8YJuwjQ", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - mangu-network

  adminer:
    image: adminer:latest
    container_name: mangu-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: lucas
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mangu-network
    profiles: ["dev", "debug"]

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mangu-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mangu-network
    profiles: ["dev", "debug"]

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  mangu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
